name: Deploy Service F

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::485898089185:role/github-actions
          aws-region: eu-west-1

      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region eu-west-1 | \
          docker login --username AWS --password-stdin 485898089185.dkr.ecr.eu-west-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t service-f:latest ./services/srv-f

      - name: Tag Docker image for ECR
        run: |
          docker tag service-f:latest 485898089185.dkr.ecr.eu-west-1.amazonaws.com/service-f:latest

      - name: Check if service repository exists
        run: |
          aws ecr create-repository --repository-name service-a --region eu-west-1 || true

      - name: Push Docker image to ECR
        run: |
          docker push 485898089185.dkr.ecr.eu-west-1.amazonaws.com/service-f:latest
