name: Deploy

on:
  push:
    branches: [ "*" ]

permissions:
  id-token: write
  contents: read
jobs:
  terraform-deploy:
    runs-on: self-hosted
    outputs:
      frontend_bucket: ${{ steps.get_outputs.outputs.FRONTEND_BUCKET }}
      cloudfront_id: ${{ steps.get_outputs.outputs.CLOUDFRONT_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Init
        run: |
          cd infra
          terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
      - name: Get Outputs
        id: get_outputs
        run: |
          echo "FRONTEND_BUCKET=$(terraform output -raw frontend_bucket)" >> $GITHUB_OUTPUT
          echo "CLOUDFRONT_ID=$(terraform output -raw frontend_cloudfront_id)" >> $GITHUB_OUTPUT

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: terraform-deploy
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Frontend
        run: |
          aws s3 sync ./frontend/build s3://${{ needs.terraform-deploy.outputs.frontend_bucket }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ needs.terraform-deploy.outputs.cloudfront_id }} --paths "/*"