name: Deploy Service B

on:
  workflow_dispatch:
  push:
    paths:
      - 'services/srv-b/**'
  pull_request:
    paths:
      - 'services/srv-b/**'

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::485898089185:role/github-actions
          aws-region: eu-west-1

      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region eu-west-1 | \
          docker login --username AWS --password-stdin 485898089185.dkr.ecr.eu-west-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t service-b:latest ./services/srv-b

      - name: Tag Docker image for ECR
        run: |
          docker tag service-b:latest 485898089185.dkr.ecr.eu-west-1.amazonaws.com/service-b:latest

      - name: Check if service repository exists
        run: |
          aws ecr create-repository --repository-name service-b --region eu-west-1 || true

      - name: Push Docker image to ECR
        run: |
          docker push 485898089185.dkr.ecr.eu-west-1.amazonaws.com/service-b:latest

      - name: Force new ECS deployment
        run: |
          aws ecs update-service --cluster demo-app-cluster --service demo-app-service_b --force-new-deployment